#!/bin/bash
execdir=.
if [ -d "../../parts" ]; then
  module=*
  moduledir=.
  basedir=../..
elif [ -d "../../../parts" ]; then
  basedir=../../..
  moduledir=..
  module=$moduledir/$(basename $(pwd))
elif [ -d "../../../../parts" ]; then
  basedir=../../../..
  moduledir=../..
  module=$moduledir/$(cd .. && basename $(pwd))
else
  echo "You have to run this from within a parts/xxxxx (repo) folder"
  echo "Or from within a parts/xxxxx/xxxxx (module) folder"
  exit
fi
if [ -f "$HOME/.pylint.cfg" ]; then
  pylintcfg="$HOME/.pylint.cfg"
else
  pylintcfg="$basedir/.pylint.cfg"
fi
msgtemplate="{abspath}:{line}: [{msg_id}({symbol}), {obj}] {msg}"
set -x
( cd $execdir && pylint --msg-template="$msgtemplate" --rcfile=$pylintcfg --init-hook="import sys; sys.path.append('$basedir/parts/odoo')" --load-plugins=pylint_odoo $module )

