#!/bin/bash
if [ ! -d parts ]; then
  echo "You have to run this from within a buildout folder"
  exit 3
fi
BUILDOUT_FILE="buildout.cfg"
if [ ! -z "$1" ]; then
  BUILDOUT_FILE="$1"
fi
if [ ! -f $BUILDOUT_FILE ]; then
  echo "$BUILDOUT_FILE not found"
  exit 3
fi
dir=$(mktemp -d)
oe-get-buildout-versions.sh . -v -f "$BUILDOUT_FILE" --skip-eggs --skip-garbage-collection > $dir/buildout.cfg
RESULT=$?
if [ $RESULT -eq 0 ]; then
  echo Successfully updated buildout.cfg.
  echo To see the changes: 'git diff'
  echo To revert the changes: 'git checkout -- buildout.cfg'
else
  echo Failed to generate buildout.cfg
  exit 3
fi
cp -f $dir/buildout.cfg $BUILDOUT_FILE


