#!/usr/bin/env python

import contextlib
import odoorpc
import netrc
import os
import requests
import ssl
import subprocess
import sys
import urllib2
import warnings
import getopt
import re
import requests
from togglwrapper import Toggl
import pprint
import json



# get login details from netRC file
netrc_info = netrc.netrc()
auth_odoosunflower = netrc_info.authenticators('odoosunflower')
if not auth_odoosunflower:
  print "In your $HOME/.netrc file place:"
  print "machine odoosunflower login myuser password mypassword"
  sys.exit(0)
odoo_username, odoo_host, odoo_password = auth_odoosunflower
auth_odootherp = netrc_info.authenticators('odootherp')
if not auth_odootherp:
  print "In your $HOME/.netrc file place:"
  print "machine odootherp login myuser password mypassword"
  sys.exit(0)
therp_username, therp_host, therp_password = auth_odootherp

# create a context to connect without checking for https cert
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE
opener = urllib2.build_opener(urllib2.HTTPSHandler(context=ctx))

# connect to Therp Odoo
therp_odoo = odoorpc.ODOO('helpdesk.therp.nl',
    protocol='jsonrpc+ssl', port=443, opener=opener)
therp_odoo.login('odointprd80-helpdesk', therp_username, therp_password)

# connect to our Odoo
sfit_odoo = odoorpc.ODOO('sunflower.1systeem.nl',
    protocol='jsonrpc+ssl', port=443, opener=opener)
sfit_odoo.login('odoo_sunflower', odoo_username, odoo_password)

therp_project_obj = therp_odoo.env['project.project']
therp_issue_obj = therp_odoo.env['project.issue']

sfit_issue_obj = sfit_odoo.env['project.issue']

therp_project_ids = therp_project_obj.search([('state', '=', 'open')])
therp_issue_ids = therp_issue_obj.search([('project_id','in',therp_project_ids),('stage_id.name', 'ilike', 'Nieuw')])

sfit_issue_ids = sfit_issue_obj.search([('remote_id', 'in', therp_issue_ids)])
sfit_remote_ids = sfit_issue_obj.browse(sfit_issue_ids).read(['remote_id'])

sfit_remote_ids = [remote.get('remote_id') for remote in sfit_remote_ids ]
issues_to_sfit = set(therp_issue_ids) - set(sfit_remote_ids)

# find id of Therp project
therp_project_id = sfit_odoo.env['project.project'].search(
    [('id', 'in', '%Therp%')])
if not therp_project_id:
  print "Therp project not found in SFIT Odoo"
  sys.exit(1)
therp_project_id = therp_project_id[0]
print "Therp project found, id = {}".format(therp_project_id)
  
issue_info = therp_issue_obj.browse(issues_to_sfit).read(['name', 'description', 'project_id'])
print 'issues to be copied from Therp ', list(issues_to_sfit)

for remote in issue_info:
    new_issue = sfit_issue_obj.create({
      'name': remote['name'],
      'description': remote['description'],
      'remote_id': remote['id'],
      'project_id': therp_project_id,
      'remote_project_id': remote['project_id']
    })
