#!/bin/bash
if [ -d "../../../parts" ]; then
  pylint --rcfile=../../../.pylint.cfg --load-plugins=pylint_odoo .
elif [ -d "../../parts" ]; then
  pylint --rcfile=../../.pylint.cfg --load-plugins=pylint_odoo *
else
  echo "You have to run this from within a parts/xxxxx (repo) folder"
  echo "Or from within a parts/xxxxx/yyyyy (module) folder"
  exit
fi
