#!/bin/bash
if [ -d "../../parts" ]; then
  pylint --rcfile=../../.pylint.cfg --init-hook='import sys; sys.path.append("../odoo")' --load-plugins=pylint_odoo *
else
  echo "You have to run this from within a parts/xxxxx (repo) folder"
  exit
fi
