#!/bin/bash
if [ ! -d "../../../parts" ]; then
  echo "You have to run this from within a parts/xxxxx/yyyyy (module) folder"
  exit
fi
module=${PWD##*/}
db=$(cat ../../../etc/odoo.cfg |grep db_name | sed -nr 's/^.*=\s//p' | awk '{$1=$1};1')
dir=$(mktemp -d)
../../../bin/start_odoo \
  --log-level=error \
  --i18n-export=$dir/$module.po \
  -l nl -d $db --modules=$module
if [ ! -f "i18n/nl.po" ]; then
  mkdir -p i18n
  /bin/cp -f $dir/$module.po i18n/nl.po
else
  /bin/cp -f i18n/nl.po $dir/$module.old.po
  msgmerge --no-fuzzy-matching --compendium $HOME/odoo_nl.po \
    -o $dir/$module.new.po \
    $dir/$module.po $dir/$module.old.po
  /bin/cp -f $dir/$module.new.po i18n/nl.po
fi

