#!/bin/bash
if [ ! -d "../../../parts" ]; then
  echo "You have to run this from within a parts/xxxxx/yyyyy (module) folder"
  exit
fi
module=${PWD##*/}
db=$(cat ../../../etc/odoo.cfg |grep db_name | sed -nr 's/^.*=\s//p' | awk '{$1=$1};1')
dir=$(mktemp -d)
../../../bin/start_odoo \
  --log-level=error \
  --i18n-export=$dir/$module.po \
  -l nl -d $db --modules=$module
/bin/cp -f i18n/nl.po $dir/$module.old.po
msgmerge --compendium $HOME/odoo_nl.po \
  -o $dir/$module.new.po \
  $dir/$module.old.po $dir/$module.po
/bin/cp -f $dir/$module.new.po i18n/nl.po

