#!/bin/bash

# getopt test
getopt --test > /dev/null
if [[ $? -ne 4 ]]; then
    echo "I’m sorry, `getopt --test` failed in this environment."
    exit 1
fi

# prefill default vars based on current folder
if [ -d "../../../parts" ]; then
  module=${PWD##*/}
  moduleparm="-u $module"
  odoo=../../../bin/start_odoo
elif [ $# -eq 0 ]; then
  echo "Usage: upgrade-module [-u module] [-d db]"
  exit
else
  odoo=bin/start_odoo
fi

# parse command line options
OPTIONS=d:u:i:
PARSED=$(getopt --options=$OPTIONS --name "$0" -- "$@")
if [[ $? -ne 0 ]]; then
    exit 2
fi
eval set -- "$PARSED"
while true; do
    case "$1" in
        -d)
            databaseparm="-d $2"
            shift 2
            ;;
        -u)
            moduleparm="-u $2"
            shift 2
            ;;
        -i)
            moduleparm="-i $2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Programming error."
            exit 3
    esac
done

# upgrade module
$odoo --xmlrpc-port=18069 --stop-after-init $moduleparm $databaseparm

