#!/bin/bash
if [ -d "../../../parts" ]; then
  module=${PWD##*/}
  odoo=../../../bin/start_odoo
elif [ $# -eq 0 ]; then
  echo "Usage: upgrade-module [module-name]"
  exit
else
  module=$1
  odoo=bin/start_odoo
fi
$odoo --xmlrpc-port=18069 -u $module --stop-after-init

