#!/bin/bash

# getopt test
getopt --test > /dev/null
if [[ $? -ne 4 ]]; then
    echo "I’m sorry, `getopt --test` failed in this environment."
    exit 1
fi

# odoo options
odoo_options=--log-level=warn

# prefill default vars based on current folder
scriptname="$(basename $0)"
if [ -d "../../../parts" ]; then
  module=${PWD##*/}
  odoo=../../../bin/start_odoo
elif [ $# -eq 0 ]; then
  echo "Usage: $0 -m [module] [-i] [-u] [-d db]"
  exit
else
  odoo=bin/start_odoo
fi

# parse command line options
moduleparm="-u"
OPTIONS=d:m:i
PARSED=$(getopt --options=$OPTIONS --name "$0" -- "$@")
if [[ $? -ne 0 ]]; then
    exit 2
fi
eval set -- "$PARSED"
while true; do
    case "$1" in
        -m)
            module="$2"
            shift 2
            ;;
        -d)
            databaseparm="-d $2"
            shift 2
            ;;
        -i)
            moduleparm="-i"
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Invalid parameter: $1."
            exit 3
    esac
done

# install or upgrade module
set -x
$odoo $odoo_options --xmlrpc-port=18069 --stop-after-init $moduleparm $module $databaseparm

